#include<iostream>
using namespace std;
main(){
	cout<<"Number 1: ";
	int number_1;
	cin>>number_1;
	cout<<"Number 2: ";
	int number_2;
	cin>>number_2;
	cout<<"Number 3: ";
	int number_3;
	cin>>number_3;
	cout<<"Number 4: ";
	int number_4;
	cin>>number_4;
	cout<<"Number 5: ";
	int number_5;
	cin>>number_5;
	cout<<"Number 6: ";
	int number_6;
	cin>>number_6;
	cout<<"Number 7: ";
	int number_7;
	cin>>number_7;
	cout<<"Number 8: ";
	int number_8;
	cin>>number_8;
	cout<<"Number 9: ";
	int number_9;
	cin>>number_9;
	cout<<"Number 10: ";
	int number_10;
	cin>>number_10;
	cout<<"Number 11: ";
	int number_11;
	cin>>number_11;
	cout<<"Number 12: ";
	int number_12;
	cin>>number_12;
	cout<<"Number 13: ";
	int number_13;
	cin>>number_13;
	cout<<"Number 14: ";
	int number_14;
	cin>>number_14;
	cout<<"Number 15: ";
	int number_15;
	cin>>number_15;
	int sum;
	sum=number_1+number_2+number_3+number_4+number_5;
	int multiplication;
	multiplication=number_6*number_7*number_8*number_9*number_10;
	int subtraction;
	subtraction=number_11-number_12-number_13-number_14-number_15;
	int add;
	add=sum+multiplication;
	int subtraction_2;
	subtraction_2=add-subtraction;
	cout<<"The final result is: "<<subtraction_2;
}